#!/bin/sh

set -euo pipefail

gitdir() {
    D="$(git rev-parse --git-dir)"
    echo "$(realpath "$D")"
}

if [ "$#" -eq 1 ] && ([ "$1" = "-h" ] || [ "$1" = "--help" ]); then
    cat - <<EOF
Usage: git-freeze [-h|--help] [--no-commit|--no-reset] ...

    Convert submodules to regular directories

    --no-commit: just give me the tree SHA1, don't commit
    --no-reset: just give me the index (implies --no-commit)
    ...: the rest parameters are passed directly to git commit
EOF
fi

if [ "$#" -eq 1 ] && [ "$1" = "--" ]; then
    printf 'echo "Freezing $P" >&2\n'
    printf 'git fetch -q %q HEAD\n' "file://$(gitdir)"
    printf 'git update-index --force-remove -- "$P"\n'
    printf 'git read-tree "--prefix=$P" FETCH_HEAD\n'
    exit 0
fi

cd "$(git rev-parse --show-toplevel)"
if [ ! -z "$(git diff-index --cached HEAD)" ]; then
    echo "Error: Index not clean." >&2
    exit 3
fi
TMPSH="$(mktemp)"
git submodule foreach --recursive "$0" -- | sed 's_^Entering _P=_' > "$TMPSH"
source "$TMPSH"
rm -f "$TMPSH"

if [ "$#" -eq 0 ]; then
    exec git commit "$@"
elif [ "$1" = "--no-commit" ]; then
    git write-tree
    git reset -q
    exit 0
elif [ "$1" = "--no-reset" ]; then
    git write-tree
    exit 0
fi
